set_property PACKAGE_PIN V16 [get_ports A]
set_property PACKAGE_PIN V17 [get_ports B]
set_property PACKAGE_PIN E19 [get_ports X]
set_property PACKAGE_PIN U16 [get_ports Y]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports X]
set_property IOSTANDARD LVCMOS33 [get_ports Y]
